[package]
name = "voyager_rs"
version = "0.0.1"
authors = ["uzushino <torattoria.mamiya@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
path = "src/lib.rs"

[dependencies]
libc = "0.2.150"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
mnist = "0.5"
rulinalg = "0.3"
rand = "*"
